DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS games;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL
);

CREATE TABLE games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    number_of_guesses INTEGER NOT NULL,
    start_time DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);